### ISSUE TITLE
Issue facing on Nexus device

### ISSUE THREAD

**Issue by VivekKumarApps** [sreekumarsh/android#7]
Hello,

Expendable listview item is not drag and drop on Google Nexus device. Please suggest what need to do?

Thanks,
Vivek

**Comment by sreekumarsh** [comment]
This is the long press not working issue rite ?

**Comment by sreekumarsh** [comment]
please give details like 
is the drag with holder on the left is working ?
what happens when you press the item and hold for 1-2 seconds ?

**Comment by tiger1990** [comment]
Hi

I had previously mentioned you this issue.
If you have time correct the issue so that it would be helpful for others.

**Comment by sreekumarsh** [comment]
sure, will be working on this

**Comment by sreekumarsh** [comment]
Check the video https://www.youtube.com/watch?v=WE-XAj5eI-A

I have tested this in nexus device with marshmallow, couldnt find any issue, could you give more details on what is the issue you get and any error or log ?

**Comment by sreekumarsh** [comment]
can i close this issue ? or do you have any updates to share ?

**Comment by ImtananRaja** [comment]
You can close it

Sent from my HTC

----- Reply message -----
