### ISSUE TITLE
Is there any way to get group view ?

### ISSUE THREAD

**Issue by bidasknakayama** [sreekumarsh/android#9]
Hello 

I enjoyed your DragNDrop project.
Could you give me your idea  ? I need your help.
After I drag & drop a list to other group, I want to change color of group Text.
Is there any way to manipulate from child to Group TextView ?

Kazu

**Comment by sreekumarsh** [comment]
if you want to change the color of a group based on whether there is a change happened in that group, just keep a flag to indicate the changed status, and you will get the on drop listener with group id.

PS : I am closing this as its not an issue.
